version: "3.3"

services:
    nginx:
        image: nginx:latest
        ports:
            - "9000:80"  # Change this line to map port 9000
        volumes:
            - ./:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - ./logs:/var/www/html/storage/logs
            - ./storage/app/public:/var/www/html/storage/app/public
        networks:
            - laravel

    db:
        image: mariadb:latest
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080

    proxy-db:
        image: "jc21/mariadb-aria:latest"
        command:
          [
              "--character-set-server=utf8mb4",
              "--collation-server=utf8mb4_unicode_ci",
              "--default-authentication-plugin=mysql_native_password",
          ]
        environment:
            MYSQL_ROOT_PASSWORD: ${PROXY_DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${PROXY_DATABASE}
            MYSQL_USER: ${PROXY_DB_MYSQL_USER}
            MYSQL_PASSWORD: ${PROXY_DB_PASSWORD}
            MYSQL_TCP_PORT: ${PROXY_DB_PORT}
        volumes:
            - ./volumes/proxy/mysql/:/var/lib/mysql
        networks:
            - laravel

    proxy:
        image: "jc21/nginx-proxy-manager:latest"
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "81:81"
        environment:
            DB_MYSQL_HOST: "proxy-db"
            DB_MYSQL_PORT: ${PROXY_DB_PORT}
            DB_MYSQL_USER: ${PROXY_DB_MYSQL_USER}
            DB_MYSQL_PASSWORD: ${PROXY_DB_PASSWORD}
            DB_MYSQL_NAME: ${PROXY_DATABASE}
        volumes:
            - ./volumes/proxy/data:/data
            - ./volumes/proxy/letsencrypt:/etc/letsencrypt
        depends_on:
            - proxy-db

networks:
    laravel:

volumes:
    dbdata:
